### ISSUE TITLE
TypeError on line 57

### ISSUE THREAD

**Issue by The-furf-of-July** [DDunda/SteamWishlistSorter#1]
After inputting my options.

Traceback (most recent call last):
  File "C:\Users\[user]\Documents\GitHub\SteamWishlistSorter\SteamWishlistSorter.py", line 57, in <module>
    if len(data.keys() < 2):
           ^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'dict_keys' and 'int'

**Comment by The-furf-of-July** [comment]
Appears to be pretty much a typo.
len(data.keys() < 2):
len(data.keys()) < 2:

**Comment by DDunda** [comment]
That looks correct, I'm unsure how I was able to run and commit with this bug in the program
