### ISSUE TITLE
Wishlist says it only has one game

### ISSUE THREAD

**Issue by The-furf-of-July** [DDunda/SteamWishlistSorter#2]
Script claims I only have one game in my wishlist.
https://store.steampowered.com/wishlist/id/The_furf_of_July/
I'm fairly confident this isn't the case, but I couldn't manage to read the code well enough to identify or solve the issue on my own.

**Comment by DDunda** [comment]
Hi there, thanks for trying out this program. It seems your steam profile has its inventory and wishlist set to private, maybe that is the issue?

**Comment by The-furf-of-July** [comment]
I legitimately didn't know it was set to private! That setting was pretty hidden. Thanks!
